node('Anible'){
   
    stage('SCM'){
        git 'https://github.com/spring-projects/spring-petclinic.git'

    }
    stage('mvn package'){
        sh 'mvn package'

    stage('archive'){
        archive 'target/*.jar'

    }
    
    }
     stage('test results'){
        junit 'target/surefire-reports/*.xml'

    }
}